apiVersion: v1
kind: Pod
metadata:
  name: data-pvc-explorer
  namespace: jchen3
spec:
  containers:
    - name: shell
      image: alpine:latest
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: data-storage
          mountPath: /data
      securityContext:
        runAsUser: 0
  volumes:
    - name: data-storage
      persistentVolumeClaim:
        claimName: data-pvc
  restartPolicy: Never
